/**
 * Module Definitions
 * All 9 modules with metadata, priority, and progress tracking
 */

import {
  MapPin,
  ShoppingCart,
  UtensilsCrossed,
  Car,
  Music,
  Backpack,
  Shield,
  DollarSign,
  Users,
} from 'lucide-react-native';
import { ModuleDefinition } from './_components';

export const MODULES: ModuleDefinition[] = [
  {
    id: 'camp_grid',
    name: 'Camp Grid',
    description: 'Design your campsite layout',
    icon: MapPin,
    color: '#28C896',
    priority: 'P1',
    isPrimary: true, // Promoted as the hero module
    isImplemented: true,
    progress: 0,
  },
  {
    id: 'supply_list',
    name: 'Supply List',
    description: "Who's bringing what",
    icon: ShoppingCart,
    color: '#C9A84C',
    priority: 'P1',
    isImplemented: true,
    progress: 0,
  },
  {
    id: 'food',
    name: 'Food Planner',
    description: 'Plan your meals',
    icon: UtensilsCrossed,
    color: '#6D30CC',
    priority: 'P2',
    isImplemented: false,
    progress: 0,
  },
  {
    id: 'travel',
    name: 'Travel',
    description: 'Rides & meetup plans',
    icon: Car,
    color: '#4A9EFF',
    priority: 'P1',
    isImplemented: true,
    progress: 0,
  },
  {
    id: 'lineup',
    name: 'Lineup',
    description: 'Vote on artists',
    icon: Music,
    color: '#F280B0',
    priority: 'P2',
    isImplemented: false,
    progress: 0,
  },
  {
    id: 'packing',
    name: 'Packing',
    description: 'Track what you packed',
    icon: Backpack,
    color: '#FFB84D',
    priority: 'P2',
    isImplemented: false,
    progress: 0,
  },
  {
    id: 'safety',
    name: 'Safety',
    description: 'Emergency info',
    icon: Shield,
    color: '#FF6B6B',
    priority: 'P1',
    isImplemented: true,
    progress: 0,
  },
  {
    id: 'budget',
    name: 'Budget',
    description: 'Track & split expenses',
    icon: DollarSign,
    color: '#B47AFF',
    priority: 'P2',
    isImplemented: false,
    progress: 0,
  },
  {
    id: 'collaboration',
    name: 'Collaboration',
    description: 'Manage crew & permissions',
    icon: Users,
    color: '#9B8340',
    priority: 'P1',
    isImplemented: false,
    progress: 0,
  },
];
