const FESTIVAL_LINEUP_PRESETS: Record<string, string[]> = {
  'EDC Las Vegas 2026': [
    '1991',
    'ABANA B2B JULIET MENDOZA',
    'ADRIAN MILLS',
    'ADRIATIQUE',
    'ADVENTURE CLUB (THROWBACK SET)',
    'ANASTAZJA',
    'ARGY',
    'ATLIENS',
    'AVALON EMERSON',
    'BOU',
    'THE CHAINSMOKERS',
    'CHARLOTTE DE WITTE',
    'CHRIS LORENZO',
    'CLOUDY',
    'COLD BLUE',
    'COSMIC GATE',
    'CULTURE SHOCK',
    'CYCLOPS',
    'DARREN PORTER',
    'DARUDE',
    'DEATHPACT',
    'DJ TENNIS B2B CHLOE CAILLET',
    'DOMINA',
    'DYEN',
    'ELI BROWN',
    'FISHER',
    'GARETH EMERY',
    'GHENGAR',
    'GORILLAT',
    'GRAVEDGR',
    'HEIDI LAWDEN B2B MASHA MAR',
    'HEYZ',
    'I HATE MODELS',
    'ILAN BLUESTONE',
    'JACKIE HOLLANDER',
    'JOHANNES SCHUSTER',
    'JOSEPH CAPRIATI',
    'JOSH BAKER',
    'KAI WACHI',
    'KOROLOVA',
    'KUKO',
    'LAIDBACK LUKE B2B CHUCKIE',
    'LEVEL UP',
    'LEVITY',
    'LUKE DEAN',
    'LUUK VAN DIJK',
    'MASSIMILIANO PAGLIARA',
    'MATTY RALPH',
    'MAX DEAN',
    'MAX DEAN B2B LUKE DEAN',
    'MEDUZA',
    'MESTIZA',
    'MPH',
    'MUZZ',
    'NICO MORENO',
    'NOTION',
    'OBSKUR',
    'OMAR+',
    'PARAMIDA',
    'PAUL VAN DYK',
    'PEGASSI',
    'PEGGY GOU',
    'PORTER ROBINSON (DJ SET)',
    'RAY VOLPE',
    'REBEKAH',
    'RIOT',
    'ROBERT HOOD',
    'RODDY LIMA',
    'SALUTE B2B CHLOE CAILLET',
    'SAN PACHO',
    'SARAH DE WARREN',
    'SERAFINA',
    'SLAMM',
    'SOFI TUKKER',
    'STACY CHRISTINE',
    'STAN CHRIST',
    'THE CARRY NATION',
    'THE OUTLAW',
    'TOMAN',
    'UNDERWORLD',
    'WALKER & ROYCE B2B VNSSA',
    'WESTEND',
    'WOOLI',
    'ABOVE & BEYOND (SUNRISE SET)',
    'AHMED SPINS',
    'ALYSSA JOLEE',
    'ANDREW RAYEL',
    'AR/CO',
    'ASTRIX',
    'AUDIOFREQ B3B CODE BLACK B3B TONESHIFTERZ',
    'AVELLO B2B DENNETT',
    'BAD BOOMBOX B2B OLLIE LISHMAN',
    'BASHKKA B2B SEDEF ADASI',
    'BAUGRUPPE90',
    'BENWAL',
    'BILLY GILLIES',
    'BOLO (SUNRISE SET)',
    'BOYS NOIZE',
    'BUNT. (IN THE ROUND)',
    'CID',
    'CLUB ANGEL',
    'CUTDWN',
    'DA TWEEKAZ',
    'DEAD X',
    'DELTA HEAVY',
    'DISCIP',
    'DJ GIGOLA B2B MCR-T',
    'DJ MANDY',
    'DOCTOR P B3B FLUX PAVILION B3B FUNTCASE',
    'DREYA V',
    'EPTIC B2B SPACE LACES',
    'FALLEN WITH MC DINO',
    'FROST CHILDREN',
    'GETTER',
    'HAAI B2B LUKE ALESSI',
    'HANNAH LAING',
    'HARDWELL',
    'HAYLA',
    'HNTR',
    'HOL!',
    'HYBRID MINDS',
    'INTERPLANETARY CRIMINAL',
    'JOHN SUMMIT',
    'JOSH BAKER B2B KETTAMA B2B PROSPA',
    'KASKADE',
    'KETTAMA',
    'LADY FAITH B2B LNY TNZ',
    'LIL TEXAS',
    'LILLY PALMER',
    'LUCIANO',
    'MADDIX',
    'MALUGI',
    'MARIA HEALY',
    'MARY DROPPINZ',
    'MATHAME',
    'MCR-T',
    'MINK',
    'MISH',
    'NOIZU',
    'OMNOM',
    'PAUL OAKENFOLD',
    'PEGGY GOU B2B KI/KI',
    'PLAYER DAVE',
    'PROSPA',
    'ROB GEE B2B LENNY DEE',
    'ROZ',
    'SAMMY VIRJI',
    'SILVIE LOTO',
    'SLUGG',
    'SNOW STRIPPERS',
    'SPRAY',
    'STEVE AOKI',
    'SUB FOCUS',
    'SUBTRONICS',
    'SUPERSTRINGS',
    'T78',
    'THE PRODIGY',
    'THE SAINTS',
    'THOMAS SCHUMACHER',
    'TIESTO',
    'VIPERACTIVE',
    'VTSS (IN THE ROUND)',
    'WAX MOTIF',
    'YDG',
    '999999999',
    'A.M.C W/ PHANTOM',
    'ADIEL',
    'AEON:MODE (SUNRISE SET)',
    'AHEE B2B LIQUID STRANGER',
    'ALISON WONDERLAND',
    'ALVES',
    'ANNA',
    'ARMIN VAN BUUREN (SUNRISE SET)',
    'BELTRAN',
    'BELTRAN B2B SIMAS',
    'BLACK TIGER SEX MACHINE',
    'BOOGIE T B2B DISTINCT MOTIVE',
    'CASSIAN',
    'CHRIS LORENZO B2B BULLET TOOTH',
    'CHRIS STUSSY',
    'CLAWZ',
    'CLOONEE',
    'CRISTOPH',
    'DABIN',
    'DJ GIGOLA',
    'DJ ISAAC',
    'DJ TENNIS B2B RED AXES',
    'EAZYBAKED',
    'ELI & FUR',
    'FRANKIE BONES',
    'FUNK TRIBU',
    'GRAVAGERZ',
    'GRIZ B2B WOOLI',
    'HAMDI',
    'INDIRA PAGANOTTO',
    'INFEKT B2B SAMPLIFIRE',
    'INNELLEA',
    'ISABELLA',
    'KEVIN DE VRIES',
    'KI/KI',
    'KINAHAU',
    'KLANGKUENSTLER',
    'KLO',
    'KREAM',
    'LAYTON GIORDANI',
    'LINSKA',
    'LU.RE',
    'MARTIN GARRIX',
    'MASSANO',
    'MORGAN SEATREE',
    "MURPHY'S LAW",
    'NICO MORENO B2B HOLY PRIEST',
    'NIGHTSTALKER WITH MC DINO',
    'NOSTALGIX',
    'PEEKABOO',
    'REBUKE',
    'RESTRICTED',
    'ROOLER',
    'SAN HOLO (WHOLESOME RIDDIM SET)',
    'SEVEN LIONS',
    'SHINGO NAKAMURA',
    'SHIP WREK',
    'SIDNEY CHARLES B2B BUSHBABY',
    'SIHK',
    'SILVA BUMPA',
    'SIPPY',
    'SKREAM',
    'SOLOMUN',
    'SUB ZERO PROJECT',
    'THE PURGE',
    'TIGA',
    'TINLICKER (DJ SET)',
    'TRACE',
    'VIEZE ASBAK',
    'VINTAGE CULTURE',
    'VIRTUAL RIOT',
    'WARFACE',
    'WARUNG',
    'WHETHAN',
    'WILLIAM BLACK',
    'YOSUF',
    'ZEDD',
  ],
  'Electric Forest 2026': [
    'SHPONGLE SIMON POSFORD LIVE',
    'ALLEYCVT',
    'FROST CHILDREN',
    'JIGITZ',
    'IVY LAB',
    'SAM GELLAITRY',
    'KASKADE',
    'KAI WACHI',
    'DEADTRONICA (ARON MAGNER OF THE DISCO BISCUITS & CLOUDCHORD)',
    'DOGS IN A PILE',
    'INIKO',
    'PROBCAUSE',
    'SHIMA',
    'BOB MOSES CLUB SET',
    'YAEJI',
    'TIFFANY DAY',
    'DANIEL ALLAN',
    'CASEY CLUB',
    'MCR-T',
    'SAMMY VIRJI',
    'DAILY BREAD',
    'ISOXO',
    'RIOT',
    'RIO KOSTA',
    'WHETHAN',
    'STARJUNK 95',
    'SULLIVAN KING',
    'MIDNIGHT GENERATION',
    'EXCISION',
    'LASZEWO',
    'MOTIFV',
    'SIPPY',
    'BRUNELLO',
    'MPH',
    'ANDY C',
    'CAIN CULTO',
    'EOTO',
    'ELI BROWN',
    'THE SPONGES',
    'CHANNEL TRES',
    'CAPOCHINO',
    'STELLER',
    'LANE 8',
    'NIGHT TAPES',
    'EFFIN',
    'JEAN DAWSON',
    'SWIMMING PAUL',
    'INJI',
    'LEVITY',
    'ODD MOB',
    'SUPERTASTE',
    'SIDEPIECE',
    'RAVENSCOON',
    'MILD MINDS',
    'GRIZ',
    'D.O.D',
    'PASSION PIT',
    'AVELLO',
    'OPPIDAN',
    'WAX MONKEY',
    'NITEPUNK',
    'DEVAULT',
    'BOMBARGO',
    'DISCO LINES',
    'WILKINSON',
    'KALEENA ZANDERS',
    'LSD CLOWNSYSTEM',
    'NIKITA THE WICKED',
    "DANIEL DONATO'S COSMIC COUNTRY",
    'DJ DIESEL B2B T-PAIN BASS DJ SET',
    'GALANTIS',
    'ROCHELLE JORDAN',
    'QRION',
    'OMNOM',
    'CLOSE FRIENDS ONLY',
    'BIPOLAR SUNSHINE',
    'WES MILLS',
    'MADEON',
    'VINCENT ANTONE',
    'WOOLI',
    'RANGER TRUCCO',
    'EGGY',
    'THE FLINTS',
    'SHIP WREK',
    'UNDERSCORES',
    'CHRIS LAKE',
    'SBTRKT DJ SET',
    'COUCH',
    'SNOW WIFE',
    'MARY VANDELUX',
    'HEYZ',
    'SAINT LUDO',
    'LSDREAM',
    'DROPPINZ',
    'MUZZ',
    'STOLEN GIN',
    'WESTEND',
    'TOURIST',
    'RIVER TIBER',
    'CHRIS LUNO',
    'PURPLE DISCO MACHINE',
    'BARDO',
    'ILLENIUM',
    'BRICKNASTY',
    'HERSHE',
    'ALL:LO COLLECTIVE: PARKBREEZY, PHEEL, TF MARZ & THOUGHT PROCESS',
    'RICHARD FINGER',
    'JACKIE HOLLANDER',
    'COSTA',
    'CREG',
    'CHMURA',
    'LYRAH',
    'GANJA WHITE NIGHT',
    "DIXON'S VIOLIN",
    'MAGOO',
    'JKYL & HYDE',
    'THE STRING CHEESE INCIDENT FEATURING A SPECIAL SHEBONGLE SHEBANG',
    'GRIZ (CHASING THE GOLDEN HOUR)',
    'LIGHTCODE BY LSDREAM',
  ],
  'Dancefestopia 2026': [
    'GRIZ',
    'EXCISION',
    'ZEDS DEAD',
    'ALLEYCVT',
    'INZO',
    'LSDREAM',
    'RAY VOLPE',
    'SULLIVAN KING',
    'AUSTERIA',
    'CALCIUM',
    'CHMURA',
    'EAZYBAKED',
    'EFFIN',
    'ELIMINATE',
    'GRABBITZ',
    'HEXA',
    'HEYZ',
    'INFEKT',
    'IZZY VADIM',
    'JAENGA',
    'JKYL & HYDE',
    'JUST AGENT',
    'KNOW GOOD.',
    'KOMPANY',
    'LAYZ',
    'LUMASI',
    'MAD DUBZ',
    'MPORT',
    'MUSHROOM CLOUD',
    'OLIVERSE',
    'OZZTIN',
    'PAPER SKIES',
    'PHRVA',
    'PRETTY SWEET',
    'PROBCAUSE',
    'RAVENSCOON',
    'REAPER',
    'RIOT TEN B2B BEAR GRILLZ',
    'SAMPLIFIRE',
    'SIPPY',
    'SMOAKLAND',
    'STAR MONSTER',
    'STELLER',
    'TYNAN',
    'USAYBFLOW',
    'WONKI WILLA',
    'WRECKNO',
    'CRANKDAT',
    'ACRYLIK X ANJ. PRESENT ANJYLIK',
    'AIR QUOTES X ITSNOTIMPORTANT PRESENT: AQXINI',
    'ALIL',
    'ALIZA',
    'AMBERSNOW',
    'DREAM & FRIENDS',
    'ELIAS TRUE',
    'ETRNL B2B PANDICORN',
    'FIELD$',
    'FILTHY TRACE',
    'GONZA',
    'HAIJACK B2B PIKNIK',
    'HALF MOON',
    'HUMAN PENGUIN B2B SAUL GUCCI',
    'INSISON',
    'KOTA WHO?',
    'KYOKEE',
    'LEKTRIK B2B SHEPPA',
    'LITEBUG',
    'MEMPO B2B CONFLIKT',
    'MIKE HO B2B HOOOPLAH',
    'MTHER',
    'MYCELIUM',
    'NICK NIEMEIER',
    'NMEZEE',
    'NOFSLINGER',
    'NOWHERE FURTHER',
    'PHANTUM',
    'PHILTHY X HOPE CIRCUIT PRESENT: PHILTH CIRCUIT',
    'RAIS3R',
    'RIDDIMSLINGER B2B BLUFF BABY',
    'RISA',
    'RISE B2B BAGZ',
    'RUGER X DARKWOOD PRESENT: FOREST FATHERS',
    'RYNO B2B SP3CIALGUEST',
    'SAVAGE HABITS B2B BOTZ & BANDZ',
    'SHARKER',
    'SLEEPER B2B THRESH',
    'SLVR FOX',
    'SPENNY',
    "Y'ALL THOUGHT X TXANA PRESENT: THOUGHTXANA",
  ],
};

const normalizeFestivalName = (value: string) =>
  value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\b20\d{2}\b/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();

const dedupeArtists = (artists: string[]): string[] => {
  const seen = new Set<string>();

  return artists.filter((artist) => {
    const normalizedArtist = artist.toLowerCase().trim();

    if (!normalizedArtist || seen.has(normalizedArtist)) {
      return false;
    }

    seen.add(normalizedArtist);
    return true;
  });
};

export function getFestivalPresetArtists(festivalName: string): string[] {
  const normalizedFestivalName = normalizeFestivalName(festivalName);

  if (!normalizedFestivalName) {
    return [];
  }

  const preset = Object.entries(FESTIVAL_LINEUP_PRESETS).find(([name]) => {
    const normalizedPresetName = normalizeFestivalName(name);

    return (
      normalizedPresetName === normalizedFestivalName ||
      normalizedPresetName.includes(normalizedFestivalName) ||
      normalizedFestivalName.includes(normalizedPresetName)
    );
  });

  if (!preset) {
    return [];
  }

  return dedupeArtists(preset[1]);
}
